#! /bin/sh

version=4.21.0
revision=1
tarball_url="https://archive.xfce.org/src/xfce/garcon/4.21/garcon-${version}.tar.xz"
tarball_blake2b="0fa1f4224aacb2e5f399aaf2899c48c59e84d470f49f383ac55d1be879a301ba77ef89cd16ba8cdce0b3eaabbeb5217397b271177c1660ed77d8594afc26746d"
hostdeps="gcc glib2 pkg-config"
deps="core-libs dbus gtk3 libxfce4ui libxfce4util"

configure() {
    meson_configure \
        -Dintrospection=false
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
