#! /bin/sh

version=2.54.7
revision=1
tarball_url="https://download.gnome.org/sources/librsvg/2.54/librsvg-${version}.tar.xz"
tarball_blake2b="8f417ba4a0c6ef3f9861d9c5c5935e27e1ce1a99c9c5f86524ac694d68fef727841f3b55b489cedb0bc86bab83bbcadb137484dcb53f4dde842573f1cf5bd1af"
imagedeps="build-essential"
hostdeps="gcc pkg-config cargo rust"
source_hostdeps="cargo rust"
deps="core-libs glib2 gdk-pixbuf cairo pango libxml2 freetype2 rust-crates"
allow_network=yes
source_allow_network=yes

prepare() {
    autotools_recursive_regen
}

build() {
    TARGET_DIR=$(pwd -P)
    rm -rf "${TARGET_DIR}/rsvg-src"
    cp -a "${source_dir}/." "${TARGET_DIR}/rsvg-src"

    cd "${TARGET_DIR}/rsvg-src"

    rm -f .cargo/config .cargo/config.toml
    sed -i '/^\[patch\.crates-io\]/d; \|path = "/base_dir/sources/rust-|d' Cargo.toml
    find . \( -name Makefile.am -o -name Makefile.in \) -exec sed -i 's/ --locked//g' {} +

    cargo_zinnia_build_env

    configure_script_path="${TARGET_DIR}/rsvg-src/configure" \
    GDK_PIXBUF_QUERYLOADERS=/bin/true \
    autotools_configure \
        --disable-introspection \
        --disable-vala \
        --disable-gtk-doc \
        --disable-tools \
        --enable-pixbuf-loader

    make -j${parallelism} bin_SCRIPTS=
}

package() {
    cd "$(pwd -P)/rsvg-src"
    DESTDIR="${dest_dir}" make install bin_SCRIPTS=

    if [ -d "${dest_dir}/sysroot" ]; then
        cp -rpv "${dest_dir}/sysroot/." "${dest_dir}/"
        rm -rf "${dest_dir}/sysroot"
    fi

    post_package_strip
}
