#! /bin/sh

from_source=gcc
revision=1
hostdeps="gcc libtool pkg-config"
imagedeps="build-essential"
deps="mlibc"
repology_id=gcc

build() {
    cd "${build_dir}"/host-builds/gcc/build

    make -j${parallelism} all-target-libgcc
}

package() {
    cd "${build_dir}"/host-builds/gcc/build

    rm -rf tmp_libgcc_dir
    mkdir tmp_libgcc_dir

    DESTDIR="$(realpath tmp_libgcc_dir)" make install-target-libgcc

    mkdir -p "${dest_dir}${prefix}"

    cp -r tmp_libgcc_dir/usr/local/lib "${dest_dir}${prefix}"/
    cp -r tmp_libgcc_dir/usr/local/${OS_TRIPLET}/* "${dest_dir}${prefix}"/
}
