#! /bin/sh

version=6.25.0
revision=1
git_url="https://github.com/KDE/ktextwidgets.git"
commit=6f7adad299720e8d8c63a4d5c3383b703084c39e
imagedeps="cmake ninja-build pkg-config libdbus-1-3 gettext"
hostdeps="gcc pkg-config cmake qt6 extra-cmake-modules kconfig kcoreaddons"
deps="core-libs kcompletion kconfig kconfigwidgets kcoreaddons ki18n kservice kwidgetsaddons qtbase6 sonnet"

configure() {
    kf6_configure \
        -DWITH_TEXT_TO_SPEECH=OFF
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
