timeout: 5

/Zinnia
	kaslr: no
	protocol: limine
	path: boot():/zinnia
	module_path: boot():/initramfs.tar
	cmdline: plainfb=true fbcon=false

/Zinnia (Shell)
	kaslr: no
	protocol: limine
	path: boot():/zinnia
	module_path: boot():/initramfs.tar
	cmdline: rd.init=/usr/bin/bash

/Debugging
	//zinnia
		kaslr: no
		protocol: limine
		path: boot():/zinnia
		module_path: boot():/initramfs.tar
		cmdline: console=tty1 plainfb=true fbcon=false ip=10.0.0.69 gateway=10.0.0.1 gdbstub=true
