#! /bin/sh

name=extra-cmake-modules
version=6.25.0
git_url="https://github.com/KDE/extra-cmake-modules.git"
commit=e10d4a6fe97c7ea51d9ed48c2a62f4205eb4c1fa

prepare() {
	sed -i '/"lib64"/s/64//' ${source_dir}/kde-modules/KDEInstallDirsCommon.cmake

	sed -e '/PACKAGE_INIT/i set(SAVE_PACKAGE_PREFIX_DIR "${PACKAGE_PREFIX_DIR}")' \
    	-e '/^include/a set(PACKAGE_PREFIX_DIR "${SAVE_PACKAGE_PREFIX_DIR}")' \
    	-i ${source_dir}/ECMConfig.cmake.in

	sed -i 's@find_program(KDE_CLANG_FORMAT_EXECUTABLE clang-format)@set(KDE_CLANG_FORMAT_EXECUTABLE "")@' \
		${source_dir}/kde-modules/KDEClangFormat.cmake
	sed -i '/^function(KDE_CONFIGURE_GIT_PRE_COMMIT_HOOK)/a\    return()' \
		${source_dir}/kde-modules/KDEGitCommitHooks.cmake

	awk '/^function\(ecm_query_qt result_variable qt_variable\)/ && !done {
		print "if(NOT QUERY_EXECUTABLE)";
		print "    find_program(_ecm_qtpaths_fallback NAMES qtpaths6 qtpaths)";
		print "    if(_ecm_qtpaths_fallback)";
		print "        set(QUERY_EXECUTABLE ${_ecm_qtpaths_fallback})";
		print "        set(_cli_option \"--query\")";
		print "    endif()";
		print "endif()";
		print "";
		done=1
	} {print}' ${source_dir}/modules/ECMQueryQt.cmake > ${source_dir}/modules/ECMQueryQt.cmake.tmp \
		&& mv ${source_dir}/modules/ECMQueryQt.cmake.tmp ${source_dir}/modules/ECMQueryQt.cmake
}
