#! /bin/sh

name=qt6
version=6.11.0
git_url="https://github.com/qt/qt5.git"
commit=b3a9d45d2d5474a39c76fddc50bf6d55bcb7858d
imagedeps="git"
allow_network=yes
shallow=no

prepare() {
    ./init-repository -f --module-subset qtbase,qtsvg,qtimageformats,qtshadertools,qtlanguageserver,qtdeclarative,qtwayland,qtmultimedia,qttools,qt5compat,qtsensors,qtpositioning,qtspeech
}
