#! /bin/sh

name=zinnia
version=a61e682d7330d2ddbf49922a952e0438fbe95352
git_url=https://github.com/zinnia-os/zinnia.git
commit=${version}
imagedeps="git"
allow_network=yes
shallow=no

prepare() {
    git submodule update --init --recursive
}
