#! /bin/sh

version=6.6.4
revision=1
git_url="https://github.com/KDE/systemsettings.git"
commit=827c136328e1ab1fc0a3f263f863d7ffa9a54228
imagedeps="cmake ninja-build pkg-config libdbus-1-3 gettext"
hostdeps="gcc pkg-config cmake qt6 extra-cmake-modules kconfig kcoreaddons kpackage kcmutils"
deps="core-libs qtbase6 qtdeclarative6 kauth kcmutils kcolorscheme kconfig kconfigwidgets kcoreaddons kcrash kdbusaddons kguiaddons ki18n kiconthemes kio kirigami kitemmodels kitemviews kjobwidgets krunner kservice kwidgetsaddons kwindowsystem kxmlgui plasma-activities"

configure() {
    kf6_configure \
        -DKF6_HOST_TOOLING=${KF6_HOST_TOOLING} \
        -DCMAKE_DISABLE_FIND_PACKAGE_KF6DocTools=ON
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
