#! /bin/sh

version=1.12.0
revision=1
git_url="https://github.com/KDE/kirigami-addons.git"
commit=ff7f00ea811ca937730f2aa6d5fca19904a8f4fb
imagedeps="cmake ninja-build pkg-config libdbus-1-3 gettext libegl1 libgl1 libx11-6 libxkbcommon0 libsystemd0"
hostdeps="gcc pkg-config cmake qt6 extra-cmake-modules kconfig kcoreaddons"
deps="core-libs kglobalaccel kguiaddons ki18n kirigami libplasma qtbase6 qtdeclarative6 qtmultimedia6"

configure() {
    kf6_configure \
        -DBUILD_EXAMPLES=OFF
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
