#! /bin/sh

version=6.11.0
git_url="https://github.com/qt/qtwayland.git"
commit=fc88dcfed73c0578d3bb562d9ff65c3aeff54c40
imagedeps="ninja-build pkg-config python3 perl"
hostdeps="gcc pkg-config cmake qt6 wayland"
deps="core-libs libxkbcommon mesa qtbase6 qtdeclarative6 wayland wayland-protocols"
revision=1

configure() {
    cmake_configure \
        -DQT_HOST_PATH=/usr/local \
        -DWaylandScanner_EXECUTABLE=/usr/local/bin/wayland-scanner \
        -DQT_BUILD_EXAMPLES=OFF \
        -DQT_BUILD_TESTS=OFF
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
