#! /bin/sh

version=4.21.0
revision=1
tarball_url="https://archive.xfce.org/src/xfce/xfce4-settings/4.21/xfce4-settings-${version}.tar.xz"
tarball_blake2b="6b1d2e78cb2650d96dc4ee4a06e5a98093cbe11347f652eb1d3d54318bca89ea85aaabff45912db1278e972ae5a0a75fafe96c28c0eac60440cd06909f4c01fd"
imagedeps="build-essential patchelf pkg-config python3 python3-distutils-extra xfce4-dev-tools"
hostdeps="gcc pkg-config glib2"
deps="core-libs garcon exo"

configure() {
    meson_configure
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
