#! /bin/sh

name=ark
version=25.12.3
revision=1
git_url="https://github.com/KDE/ark.git"
commit=f18aeee7dad0c589dd6bb23535de511383c5a5fc
imagedeps="cmake ninja-build pkg-config libdbus-1-3 gettext"
hostdeps="gcc pkg-config cmake qt6 extra-cmake-modules kconfig kcoreaddons"
deps="core-libs qtbase6 zlib libarchive karchive kbookmarks kconfig kconfigwidgets kcoreaddons kcrash kdbusaddons kfilemetadata ki18n kio kitemmodels kiconthemes kparts kpty kservice kwidgetsaddons kwindowsystem"

configure() {
    kf6_configure \
        -DKF6_HOST_TOOLING=${KF6_HOST_TOOLING} \
        -DBUILD_DOC=OFF \
        -DCMAKE_DISABLE_FIND_PACKAGE_LibZip=ON \
        -DCMAKE_DISABLE_FIND_PACKAGE_KF6DocTools=ON
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
