#! /bin/sh

name=attica
version=6.25.0
revision=1
git_url="https://github.com/KDE/attica.git"
commit=e8554442299695d758643f5ac41bcc3f46b9cc06
imagedeps="cmake ninja-build pkg-config"
hostdeps="gcc pkg-config cmake qt6 extra-cmake-modules"
deps="core-libs qtbase6"

configure() {
    kf6_configure
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
