#! /bin/sh

name=dolphin
version=25.12.3
revision=1
git_url="https://github.com/KDE/dolphin.git"
commit=5e0a9f6477424dcb3fdb8cdf1c9d5ebcba36424d
imagedeps="cmake ninja-build pkg-config libdbus-1-3 gettext"
hostdeps="gcc pkg-config cmake qt6 extra-cmake-modules kconfig kcoreaddons kpackage kcmutils"
deps="core-libs kbookmarks kcmutils kcodecs kcolorscheme kcompletion kconfig kconfigwidgets kcoreaddons kcrash kdbusaddons kfilemetadata kguiaddons ki18n kiconthemes kio knewstuff knotifications kparts kservice ktextwidgets kwidgetsaddons kwindowsystem kxmlgui solid qtbase6 zlib"

configure() {
    kf6_configure \
        -DKF6_HOST_TOOLING=${KF6_HOST_TOOLING} \
        -DCMAKE_DISABLE_FIND_PACKAGE_KF6UserFeedback=ON \
        -DCMAKE_DISABLE_FIND_PACKAGE_PackageKitQt6=ON \
        -DCMAKE_DISABLE_FIND_PACKAGE_KF6Baloo=ON \
        -DCMAKE_DISABLE_FIND_PACKAGE_KF6BalooWidgets=ON \
        -DCMAKE_DISABLE_FIND_PACKAGE_KF6DocTools=ON
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
