#! /bin/sh

name=extra-cmake-modules
from_source=extra-cmake-modules
revision=1
imagedeps="pkg-config"
hostdeps="gcc pkg-config cmake"
deps="core-libs"

configure() {
    cmake_configure \
        -DBUILD_TESTING=OFF
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
