#! /bin/sh

name=frameworkintegration
version=6.25.0
revision=1
git_url="https://github.com/KDE/frameworkintegration.git"
commit=e30525526ec05314ba459806cf674e83a7f9e109
imagedeps="cmake ninja-build pkg-config libdbus-1-3 gettext"
hostdeps="gcc pkg-config cmake qt6 extra-cmake-modules kconfig kcoreaddons"
deps="core-libs kcolorscheme kconfig ki18n kiconthemes knewstuff knotifications kpackage kwidgetsaddons qtbase6"

configure() {
    kf6_configure
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
