#! /bin/sh

name=frigg
version=b0dbea66bc19f7c5546f0039a3be842feb02678c
revision=1
git_url="https://github.com/managarm/frigg.git"
commit=${version}
imagedeps="meson ninja-build"
hostdeps="pkg-config"

configure() {
    meson_configure \
        --includedir=share/frigg/include \
        -Dbuild_tests=disabled
}

build() {
    ninja -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" ninja install

    post_package_strip
}
