#! /bin/sh

name=gst-plugins-base
version=1.26.11
revision=1
tarball_url="https://gstreamer.freedesktop.org/src/gst-plugins-base/gst-plugins-base-${version}.tar.xz"
tarball_blake2b="d74d013e709aff8225ce2e0ebda7aa70f8811ac7e614de491080ae4026b348c19e6f8ed700f8e4dafef12d600dc2fdd5343413d45291c539eb0e3bc70dfecf21"
imagedeps="libglib2.0-dev bison flex liborc-0.4-dev"
hostdeps="gcc pkg-config"
deps="core-libs glib2 gstreamer orc pango graphene mesa libdrm libx11 libxext zlib"

configure() {
    meson_configure \
        -Dintrospection=disabled \
        -Dtests=disabled \
        -Dexamples=disabled \
        -Ddoc=disabled \
        -Dnls=disabled \
        -Dorc=enabled \
        -Dgl=enabled \
        -Dgl_platform=egl \
        -Dgl_winsys=x11 \
        -Dpango=enabled \
        -Dx11=enabled \
        -Dalsa=disabled \
        -Dcdparanoia=disabled \
        -Dlibvisual=disabled \
        -Dtremor=disabled \
        -Dvorbis=disabled \
        -Dtheora=disabled \
        -Dopus=disabled \
        -Dogg=disabled
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
