#! /bin/sh

name=kauth
version=6.25.0
revision=1
git_url="https://github.com/KDE/kauth.git"
commit=17b71d4159c00294d2071a910d43bce161596e02
imagedeps="cmake ninja-build pkg-config libdbus-1-3 gettext"
hostdeps="gcc pkg-config cmake qt6 extra-cmake-modules kconfig kcoreaddons"
deps="core-libs kcoreaddons qtbase6"

configure() {
    kf6_configure
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
