#! /bin/sh

name=kcmutils
version=6.25.0
revision=1
git_url="https://github.com/KDE/kcmutils.git"
commit=cc012aab1b623dd32ce5f870e02958ec977ae6ce
imagedeps="cmake ninja-build pkg-config libdbus-1-3 gettext libegl1 libgl1 libx11-6 libxkbcommon0 libsystemd0"
hostdeps="gcc pkg-config cmake qt6 extra-cmake-modules kconfig kcoreaddons"
deps="core-libs kconfig kconfigwidgets kcoreaddons kguiaddons ki18n kio kitemviews kwidgetsaddons kxmlgui qtbase6 qtdeclarative6"

configure() {
    kf6_configure
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
