#! /bin/sh

name=kcodecs
version=6.25.0
revision=1
git_url="https://github.com/KDE/kcodecs.git"
commit=133fd538d7698512ec1a24befdc7762991dd8df5
imagedeps="cmake ninja-build pkg-config"
hostdeps="gcc pkg-config cmake qt6 extra-cmake-modules"
deps="core-libs qtbase6"

configure() {
    kf6_configure
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
