#! /bin/sh

name=kcoreaddons
version=6.25.0
revision=1
git_url="https://github.com/KDE/kcoreaddons.git"
commit=447250fb061d6a866eeef9ae3c21b627244b198a
imagedeps="cmake ninja-build pkg-config libdbus-1-3"
hostdeps="gcc pkg-config cmake qt6 extra-cmake-modules"
deps="core-libs qtbase6 qtdeclarative6"

configure() {
    kf6_configure
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
