#! /bin/sh

name=kdbusaddons
version=6.25.0
revision=1
git_url="https://github.com/KDE/kdbusaddons.git"
commit=d4e685828b1e610b7e9feb846b704542efdbc375
imagedeps="cmake ninja-build pkg-config libdbus-1-3"
hostdeps="gcc pkg-config cmake qt6 extra-cmake-modules"
deps="core-libs qtbase6 dbus"

configure() {
    kf6_configure
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
