#! /bin/sh

name=kded
version=6.25.0
revision=1
git_url="https://github.com/KDE/kded.git"
commit=b9f2797aeac1e693bb5a285f8ab24c28ebf73067
imagedeps="cmake ninja-build pkg-config libdbus-1-3 gettext"
hostdeps="gcc pkg-config cmake qt6 extra-cmake-modules kconfig kcoreaddons"
deps="core-libs kconfig kcoreaddons kcrash kdbusaddons kservice qtbase6"

configure() {
    kf6_configure
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
