#! /bin/sh

name=kglobalaccel
version=6.25.0
revision=1
git_url="https://github.com/KDE/kglobalaccel.git"
commit=314a2ed005d61f81a7a4e8b59c55a36bbbdcdd5c
imagedeps="cmake ninja-build pkg-config libdbus-1-3"
hostdeps="gcc pkg-config cmake qt6 extra-cmake-modules"
deps="core-libs qtbase6 qtdeclarative6 libx11 libxcb"

configure() {
    kf6_configure
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
