#! /bin/sh

name=kguiaddons
version=6.25.0
revision=1
git_url="https://github.com/KDE/kguiaddons.git"
commit=f9fd9583fd2c235678f811ba13a7114fd47e0e56
imagedeps="cmake ninja-build pkg-config"
hostdeps="gcc pkg-config cmake qt6 extra-cmake-modules wayland"
deps="core-libs qtbase6 qtwayland6 wayland wayland-protocols plasma-wayland-protocols libice libx11 libxcb xorg-proto"

configure() {
    kf6_configure \
        -DWaylandScanner_EXECUTABLE=/usr/local/bin/wayland-scanner
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
