#! /bin/sh

name=kholidays
version=6.25.0
revision=1
git_url="https://github.com/KDE/kholidays.git"
commit=7218a304119dd407dd09e205cc1e902e5e5e0ec3
imagedeps="cmake ninja-build pkg-config"
hostdeps="gcc pkg-config cmake qt6 extra-cmake-modules"
deps="core-libs qtbase6 qtdeclarative6"

configure() {
    kf6_configure
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
