#! /bin/sh

name=ki18n
version=6.25.0
revision=1
git_url="https://github.com/KDE/ki18n.git"
commit=87d5c227985b43ac9173b774d85cf0fac9fccd6d
imagedeps="cmake ninja-build pkg-config gettext"
hostdeps="gcc pkg-config cmake qt6 extra-cmake-modules"
deps="core-libs iso-codes libintl qtbase6 qtdeclarative6"

configure() {
    kf6_configure
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
