#! /bin/sh

name=knewstuff
version=6.25.0
revision=1
git_url="https://github.com/KDE/knewstuff.git"
commit=f7c6d392e06aad8a32de6c4b5c5ff75a2ecb62bc
imagedeps="cmake ninja-build pkg-config libdbus-1-3 gettext libegl1 libgl1 libx11-6 libxkbcommon0 libsystemd0"
hostdeps="gcc pkg-config cmake qt6 extra-cmake-modules kconfig kcoreaddons"
deps="core-libs attica karchive kconfig kcoreaddons ki18n kirigami kpackage kwidgetsaddons qtbase6 qtdeclarative6"

configure() {
    kf6_configure
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
