#! /bin/sh

name=knotifications
version=6.25.0
revision=1
git_url="https://github.com/KDE/knotifications.git"
commit=cffe2be53334a2e716cad7afaabde7855027de5d
imagedeps="cmake ninja-build pkg-config libdbus-1-3"
hostdeps="gcc pkg-config cmake qt6 extra-cmake-modules"
deps="core-libs kconfig qtbase6 qtdeclarative6"

configure() {
    kf6_configure
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
