#! /bin/sh

name=konsole
version=25.12.3
revision=1
git_url="https://github.com/KDE/konsole.git"
commit=cd42390ed23b2f5b56d54644c046a2fdb32c454c
imagedeps="cmake ninja-build pkg-config libdbus-1-3 gettext libegl1 libgl1 libx11-6 libxkbcommon0 libsystemd0"
hostdeps="gcc pkg-config cmake qt6 extra-cmake-modules kconfig kcoreaddons"
deps="core-libs icu kbookmarks kconfig kconfigwidgets kcoreaddons kcrash kdbusaddons kglobalaccel kguiaddons ki18n kiconthemes kio knewstuff knotifications knotifyconfig kparts kpty kservice ktextwidgets kwidgetsaddons kwindowsystem kxmlgui qt5compat qtbase6 qtdeclarative6 qtmultimedia6 zlib"

configure() {
    kf6_configure \
        -DKF6_HOST_TOOLING=${KF6_HOST_TOOLING}
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
