#! /bin/sh

name=kpackage
version=6.25.0
revision=1
git_url="https://github.com/KDE/kpackage.git"
commit=92f122e25eafa3e21e42217a58097d6f74fd69c8
imagedeps="cmake ninja-build pkg-config libdbus-1-3 gettext"
hostdeps="gcc pkg-config cmake qt6 extra-cmake-modules kconfig kcoreaddons"
deps="core-libs karchive kcoreaddons ki18n qtbase6"

configure() {
    kf6_configure
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
