#! /bin/sh

name=kparts
version=6.25.0
revision=1
git_url="https://github.com/KDE/kparts.git"
commit=f8f596fab1b37fa63ead662ba08fc99ba342c309
imagedeps="cmake ninja-build pkg-config libdbus-1-3 gettext"
hostdeps="gcc pkg-config cmake qt6 extra-cmake-modules kconfig kcoreaddons"
deps="core-libs kconfig kcoreaddons ki18n kiconthemes kio kjobwidgets kservice kwidgetsaddons kxmlgui qtbase6"

configure() {
    kf6_configure
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
