#! /bin/sh

name=kscreen
version=6.6.4
revision=1
git_url="https://github.com/KDE/kscreen.git"
commit=705bfb32313f892a811bcf42c3e3161e3ac8f3b4
imagedeps="cmake ninja-build pkg-config libdbus-1-3 gettext libxcb1"
hostdeps="gcc pkg-config cmake qt6 extra-cmake-modules kconfig kcoreaddons kpackage kcmutils wayland"
deps="core-libs qtbase6 qtdeclarative6 qtwayland6 libkscreen libplasma layer-shell-qt wayland-protocols kconfig kconfigwidgets kcoreaddons kcrash kdbusaddons kdeclarative kglobalaccel ki18n kcmutils kirigami ksvg kxmlgui plasma-activities libx11 libxcb xcb-util"

configure() {
    kf6_configure \
        -DKF6_HOST_TOOLING=${KF6_HOST_TOOLING} \
        -DWaylandScanner_EXECUTABLE=/usr/local/bin/wayland-scanner \
        -DCMAKE_DISABLE_FIND_PACKAGE_KF6DocTools=ON
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
