#! /bin/sh

name=kservice
version=6.25.0
revision=1
git_url="https://github.com/KDE/kservice.git"
commit=80c841c1b5fb7e7050ef1737bf9c379bd65f4cba
imagedeps="cmake ninja-build pkg-config libdbus-1-3 gettext"
hostdeps="gcc pkg-config cmake qt6 extra-cmake-modules kconfig kcoreaddons"
deps="core-libs kconfig kcoreaddons kdbusaddons ki18n qtbase6"

configure() {
    kf6_configure
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
