#! /bin/sh

name=kwallet
version=6.25.0
revision=1
git_url="https://github.com/KDE/kwallet.git"
commit=973b7f30b9e75ca060c1a4274c9ff41744f70dfb
imagedeps="cmake ninja-build pkg-config libdbus-1-3 gettext libegl1 libgl1 libx11-6 libxkbcommon0 libsystemd0"
hostdeps="gcc pkg-config cmake qt6 extra-cmake-modules kconfig kcoreaddons"
deps="core-libs kcolorscheme kconfig kcoreaddons kcrash kdbusaddons ki18n knotifications kservice kwidgetsaddons kwindowsystem libgcrypt qtbase6"

configure() {
    kf6_configure \
        -DKF6_HOST_TOOLING=${KF6_HOST_TOOLING} \
        -DBUILD_KSECRETD=OFF \
        -DBUILD_KWALLETD=OFF \
        -DBUILD_KWALLET_QUERY=OFF
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
