#! /bin/sh

name=kwidgetsaddons
version=6.25.0
revision=1
git_url="https://github.com/KDE/kwidgetsaddons.git"
commit=92f79dea45319a749445721da0a51b2210924477
imagedeps="cmake ninja-build pkg-config"
hostdeps="gcc pkg-config cmake qt6 extra-cmake-modules"
deps="core-libs qtbase6"

configure() {
    kf6_configure
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
