#! /bin/sh

name=kwin
version=6.6.4
revision=1
git_url="https://github.com/KDE/kwin.git"
commit=41192ce249dc712e14b306b5b2e2b4752042cfba
imagedeps="build-essential cmake ninja-build pkg-config libdbus-1-3 gettext libegl1 libgl1 libx11-6 libxkbcommon0 libsystemd0"
hostdeps="gcc pkg-config cmake qt6 extra-cmake-modules kconfig kcoreaddons kpackage kcmutils wayland"
deps="core-libs hwdata kauth kcmutils kcolorscheme kconfig kconfigwidgets kcoreaddons kcrash kdbusaddons kdeclarative kdecoration kglobalaccel kglobalacceld kguiaddons ki18n kidletime knewstuff knighttime kpackage kservice ksvg kwayland kwidgetsaddons kwindowsystem kxmlgui lcms2 libcanberra libdisplay-info libdrm libei libinput libplasma libxcvt plasma-activities qt5compat qtbase6 qtdeclarative6 qtsensors6 qtshadertools6 qtsvg6 qttools6 qtwayland6 xwayland"

configure() {
    kf6_configure \
        -DKWIN_BUILD_SCREENLOCKER=OFF \
        -DKWIN_BUILD_GAMECONTROLLER=OFF \
        -DWaylandScanner_EXECUTABLE=/usr/local/bin/wayland-scanner \
        -DKF6_HOST_TOOLING=${KF6_HOST_TOOLING}
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
