#! /bin/sh

name=kxmlgui
version=6.25.0
revision=1
git_url="https://github.com/KDE/kxmlgui.git"
commit=ab4b8dad176d4fa36c5702c89164ea81f70bb005
imagedeps="cmake ninja-build pkg-config libdbus-1-3 gettext"
hostdeps="gcc pkg-config cmake qt6 extra-cmake-modules kconfig kcoreaddons"
deps="core-libs kconfig kconfigwidgets kcoreaddons kglobalaccel kguiaddons ki18n kiconthemes kitemviews kwidgetsaddons qtbase6"

configure() {
    kf6_configure
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
