#! /bin/sh

name=libcroco
version=0.6.13
revision=1
tarball_url="https://download.gnome.org/sources/libcroco/0.6/libcroco-${version}.tar.xz"
tarball_blake2b="511212f1849343d55104cc6d17662cacd524bae098bab12d6db58df41710c8dca2c5beb7a37e42feac6d856934a07feb3d11c55dc74ba055e21066f2bdefb260"
hostdeps="gcc pkg-config"
deps="core-libs glib2 libxml2"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure \
        --disable-gtk-doc
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
