#! /bin/sh

name=libqalculate
version=5.10.0
revision=1
git_url="https://github.com/Qalculate/libqalculate.git"
commit=a1181d86c0715fce9c2cb6bbcd59b1d2cf10e88a
imagedeps="build-essential autoconf automake libtool pkg-config gettext"
source_imagedeps="autoconf automake libtool pkg-config gettext"
hostdeps="gcc pkg-config"
deps="core-libs curl gmp icu libiconv libxml2 mpfr readline"

prepare() {
    cd "${source_dir}"
    autoreconf -fvi
    autotools_recursive_regen
}

configure() {
    autotools_configure \
        --disable-static \
        --disable-nls
}

build() {
    make -j${parallelism}
}

package() {
    make install DESTDIR="${dest_dir}"

    post_package_strip
}
