#! /bin/sh

name=libudev
version=2026.05
revision=1
git_url="https://github.com/wulf7/libudev-devd.git"
commit="0f2c177600a5d2d89ecbc6fa4c1272e42ab224fb"
hostdeps="gcc pkg-config"
deps="core-libs libevdev"

configure() {
    # libudev-devd's tree.h uses the GNU `typeof` keyword, which the upstream
    # default of c_std=c11 rejects. Build as GNU C11 instead.
    meson_configure \
        -Dc_std=gnu11
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
