#! /bin/sh

name=libxklavier
version=5.4
revision=1
tarball_url="https://people.freedesktop.org/~svu/libxklavier-${version}.tar.bz2"
tarball_blake2b="3cd109c6200ef977533d39b1362c33f871c2cd0b011779b726546aa7dc95bf7dc89931dff7ca2e9a012a51aeec602a53df499591ab30e1dd813fcc823318a2e2"
imagedeps="build-essential pkg-config libglib2.0-dev-bin"
hostdeps="gcc pkg-config"
deps="core-libs glib2 libxml2 libx11 libxi libxkbfile xkeyboard-config iso-codes"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure \
        --disable-static \
        --disable-introspection \
        --disable-gtk-doc \
        --disable-vala \
        --with-xkb-base=/usr/share/X11/xkb
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
