#! /bin/sh

name=lightdm
version=1.32.0
revision=11
tarball_url="https://github.com/canonical/lightdm/releases/download/${version}/lightdm-${version}.tar.xz"
tarball_blake2b="90191559895a58e2c5892705ea95766aaaaa87d3470f1372ab90fcf3991d27f9280d5bbabe0cfce70e25f960d63c1e7eab7beeeb501341996afd155788cbe1c7"
imagedeps="intltool itstool"
hostdeps="gcc pkg-config"
deps="core-libs glib2 libgcrypt libx11 libxcb libxklavier openpam dbus xorg-server xorg-xauth adwaita-icon-theme"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure \
        --disable-static \
        --disable-introspection \
        --disable-vala \
        --disable-liblightdm-qt5 \
        --disable-tests \
        --disable-gtk-doc \
        --disable-libaudit \
        --disable-nls \
        --with-greeter-user=root \
        --with-greeter-session=lightdm-gtk-greeter \
        --with-user-session=weston
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    # lightdm's stock PAM stacks reference Linux-PAM modules that OpenPAM does not provide.
    rm -f "${dest_dir}/etc/pam.d/lightdm" \
          "${dest_dir}/etc/pam.d/lightdm-greeter" \
          "${dest_dir}/etc/pam.d/lightdm-autologin"

    post_package_strip
}
