#! /bin/sh

name=limine
version=12.4.0
revision=1
tarball_url="https://github.com/Limine-Bootloader/Limine/releases/download/v${version}/limine-${version}.tar.gz"
tarball_blake2b="4c6cf77387a592695607f2fd3552bddafaeb98c23a4822b4ecdc275f52dc5364ebe3242798a4b4293d1ae1c266d0ca77fae5cee1e9ebc8e7e89736f3ae8ef5a7"
imagedeps="clang build-essential lld llvm mtools nasm"
hostdeps="gcc binutils autoconf automake"
deps="core-libs"
source_hostdeps="automake autoconf"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure \
        --enable-all
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
