#! /bin/sh

name=mesa
version=25.3.0
revision=2
tarball_url="https://archive.mesa3d.org/mesa-${version}.tar.xz"
tarball_blake2b="54cd99f9a4f14bf070f5525a91a776f0b7042ce7c056bf8db388baa5c98e0065799cdc376c0c42205b08eff18f252b6e7be5987e44fb628b97a360a7e89c300f"
imagedeps="python3-mako python3-yaml glslang-tools pkg-config"
hostdeps="gcc pkg-config wayland"
deps="core-libs libdrm libexpat libglvnd libx11 libxcb libxext libxfixes libxrandr libxshmfence libxxf86vm llvm xcb-util-keysyms wayland-protocols zlib zstd"

configure() {
    meson_configure \
        -Db_ndebug=true \
        -Dbuild-tests=false \
        -Ddri-drivers-path=/usr/lib/dri \
        -Dshared-glapi=enabled \
        -Dexpat=enabled \
        -Dgbm=enabled \
        -Dgles1=enabled \
        -Dgles2=enabled \
        -Dglvnd=enabled \
        -Degl=enabled \
        -Dllvm=enabled \
        -Dzstd=enabled \
        -Dvideo-codecs=all_free \
        -Dvulkan-drivers="" \
        -Dgallium-drivers=softpipe,llvmpipe
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
