#! /bin/sh

name=mlibc
revision=1
from_source=mlibc
imagedeps="build-essential meson ninja-build"
hostdeps="gcc pkg-config libgcc-binaries"
builddeps="frigg libsmarter"
deps="mlibc-headers"
allow_network=yes

configure() {
        CFLAGS="$TARGET_CFLAGS" \
        CXXFLAGS="$TARGET_CXXFLAGS" \
        LDFLAGS="$TARGET_LDFLAGS -Wl,/usr/local/libgcc-binaries/libgcc-${JINX_ARCH}.a" \
    meson_configure_noflags \
        -Dno_headers=true \
        -Ddefault_library=both \
        -Dlibgcc_dependency=false
}

build() {
    ninja -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" ninja install
}
