#! /bin/sh

name=plasma-wayland-protocols
version=1.20.0
revision=1
git_url="https://github.com/KDE/plasma-wayland-protocols.git"
commit=6fee13b7c0b25d4619e20090f4a178fc2b460be7
imagedeps="cmake ninja-build pkg-config"
hostdeps="gcc pkg-config cmake extra-cmake-modules qt6"
deps="core-libs"

configure() {
    kf6_configure
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
