#! /bin/sh

name=plasma-workspace
version=6.6.4
revision=2
git_url="https://github.com/KDE/plasma-workspace.git"
commit=7bfae4aa566473dfd437e05dddfa54a10b118ce7
imagedeps="build-essential cmake ninja-build pkg-config libdbus-1-3 gettext libegl1 libgl1 libx11-6 libxkbcommon0 libsystemd0"
hostdeps="gcc pkg-config cmake qt6 extra-cmake-modules kconfig kcoreaddons kpackage kcmutils wayland"
deps="core-libs breeze fontconfig icu iso-codes karchive kauth kbookmarks kcmutils kcolorscheme kcompletion kconfig kconfigwidgets kcoreaddons kcrash kdbusaddons kdeclarative kded kglobalaccel kglobalacceld kguiaddons ki18n kiconthemes kidletime kio kirigami-addons kitemmodels kitemviews kjobwidgets knewstuff knotifications knotifyconfig kpackage kparts krunner kscreenlocker kservice kstatusnotifieritem ksvg ktexteditor ktextwidgets kunitconversion kwallet kwayland kwidgetsaddons kwin kwindowsystem kxmlgui layer-shell-qt libcanberra libice libkscreen libksysguard libplasma libqalculate libsm libx11 libxau libxcb libxcursor libxfixes libxft libxrender libxtst plasma-activities plasma-activities-stats plasma-wayland-protocols plasma5support prison qcoro qt5compat qtbase6 qtdeclarative6 qtlocation6 qtpositioning6 qtshadertools6 qtsvg6 solid wayland xcb-util xcb-util-image"

configure() {
    kf6_configure \
        -DWITH_X11=ON \
        -DKF6_HOST_TOOLING=${KF6_HOST_TOOLING} \
        -DWaylandScanner_EXECUTABLE=/usr/local/bin/wayland-scanner \
        -DCMAKE_DISABLE_FIND_PACKAGE_PackageKitQt6=ON \
        -DCMAKE_DISABLE_FIND_PACKAGE_Systemd=ON \
        -DCMAKE_DISABLE_FIND_PACKAGE_systemd=ON \
        -DGLIBC_LOCALE_GEN=OFF \
        -DGLIBC_LOCALE_PREGENERATED=OFF \
        -DBUILD_CAMERAINDICATOR=OFF
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    cp -rp "${base_dir}/extras/plasma-workspace/." "${dest_dir}/"
    chmod 0755 "${dest_dir}/usr/bin/startplasma-zinnia"

    post_package_strip
}
