#! /bin/sh

name=plasma5support
version=6.6.4
revision=1
git_url="https://github.com/KDE/plasma5support.git"
commit=2a21872bd6c0073a0532229abbf294f22472a43c
imagedeps="cmake ninja-build pkg-config libdbus-1-3 gettext libegl1 libgl1 libx11-6 libxkbcommon0 libsystemd0"
hostdeps="gcc pkg-config cmake qt6 extra-cmake-modules kconfig kcoreaddons"
deps="core-libs kconfig kcoreaddons kguiaddons kholidays ki18n kidletime kio knotifications kservice kunitconversion libksysguard libx11 plasma-activities qtbase6 qtdeclarative6 solid"

configure() {
    kf6_configure \
        -DWITH_X11=ON
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
