#! /bin/sh

name=plasma-integration
version=6.6.4
revision=1
git_url="https://github.com/KDE/plasma-integration.git"
commit=73a57841e0c94c2b1c28274be34d5792beeb611a
imagedeps="cmake ninja-build pkg-config libdbus-1-3 gettext libegl1 libgl1 libx11-6 libxkbcommon0 libsystemd0"
hostdeps="gcc pkg-config cmake qt6 extra-cmake-modules kconfig kcoreaddons wayland"
deps="core-libs kconfig kconfigwidgets kcoreaddons kguiaddons ki18n kiconthemes kio knotifications kstatusnotifieritem kwidgetsaddons kwindowsystem kxmlgui qtbase6 qtdeclarative6"

configure() {
    kf6_configure \
        -DBUILD_QT6=ON \
        -DBUILD_QT5=OFF \
        -DKF6_HOST_TOOLING=${KF6_HOST_TOOLING} \
        -DWaylandScanner_EXECUTABLE=/usr/local/bin/wayland-scanner
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
