#! /bin/sh

name=plasma6-desktop
version=0.0
revision=2
deps="plasma-workspace plasma-desktop plasma-integration kwin kscreenlocker kactivitymanagerd breeze breeze-icons qqc2-desktop-style qqc2-breeze-style minilogind lightdm lightdm-gtk-greeter dbus seatd mesa xwayland xkeyboard-config ttf-dejavu ttf-liberation"
skip_pkg_check=yes
