#! /bin/sh

name=prison
version=6.25.0
revision=1
git_url="https://github.com/KDE/prison.git"
commit=b7e5b396c8405a74546a3351bff156e8df13dee7
imagedeps="cmake ninja-build pkg-config gettext libegl1 libgl1 libx11-6 libxkbcommon0 libsystemd0"
hostdeps="gcc pkg-config cmake qt6 extra-cmake-modules"
deps="core-libs libdmtx qrencode qtbase6 qtdeclarative6 qtmultimedia6 zxing-cpp"

configure() {
    kf6_configure \
        -DBUILD_EXAMPLES=OFF
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
