#! /bin/sh

name=qqc2-desktop-style
version=6.25.0
revision=1
git_url="https://github.com/KDE/qqc2-desktop-style.git"
commit=15d1076f5b884a49ebdaac3ba89c4c7448d7bde8
imagedeps="cmake ninja-build pkg-config libdbus-1-3 gettext libegl1 libgl1 libx11-6 libxkbcommon0 libsystemd0"
hostdeps="gcc pkg-config cmake qt6 extra-cmake-modules kconfig kcoreaddons"
deps="core-libs kcolorscheme kconfig kiconthemes kirigami qtbase6 qtdeclarative6 sonnet"

configure() {
    kf6_configure
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
