#! /bin/sh

name=qtmultimedia6
version=6.11.0
git_url="https://github.com/qt/qtmultimedia.git"
commit=54632b43cde46b31993e4590ce767e18dc471b84
imagedeps="ninja-build pkg-config python3 perl libegl1 libgl1 libx11-6 libxkbcommon0 libdbus-1-3 libsystemd0"
hostdeps="gcc pkg-config cmake qt6"
deps="core-libs qtbase6 qtdeclarative6 qtshadertools6"
revision=1

configure() {
    cmake_configure \
        -DQT_HOST_PATH=/usr/local \
        -DQT_BUILD_EXAMPLES=OFF \
        -DQT_BUILD_TESTS=OFF \
        -DFEATURE_gstreamer=OFF \
        -DFEATURE_ffmpeg=OFF \
        -DFEATURE_alsa=OFF \
        -DFEATURE_pulseaudio=OFF \
        -DFEATURE_pipewire=OFF
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
