#! /bin/sh

name=qtsensors6
version=6.11.0
git_url="https://github.com/qt/qtsensors.git"
commit=92ed021507d4f8c38e0e9548db97c8dd039829d9
imagedeps="ninja-build pkg-config python3 perl"
hostdeps="gcc pkg-config cmake qt6"
deps="core-libs qtbase6 qtdeclarative6"
revision=1

configure() {
    cmake_configure \
        -DQT_HOST_PATH=/usr/local \
        -DQT_BUILD_EXAMPLES=OFF \
        -DQT_BUILD_TESTS=OFF
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
