#! /bin/sh

name=qtspeech6
version=6.11.0
git_url="https://github.com/qt/qtspeech.git"
commit=781970f4301d62eecfd85dfedb8432674ea24bb5
imagedeps="ninja-build pkg-config python3 perl"
hostdeps="gcc pkg-config cmake qt6"
deps="core-libs qtbase6 qtdeclarative6 qtmultimedia6"
revision=1

configure() {
    cmake_configure \
        -DQT_HOST_PATH=/usr/local \
        -DQT_BUILD_EXAMPLES=OFF \
        -DQT_BUILD_TESTS=OFF \
        -DFEATURE_speechd=OFF \
        -DFEATURE_flite=OFF \
        -DFEATURE_flite_alsa=OFF
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
