#! /bin/sh

name=rust-nix
skip_pkg_check=yes
version=0.30.1
revision=1
tarball_url="https://github.com/nix-rust/nix/archive/refs/tags/v${version}.tar.gz"
tarball_blake2b="dabb6f5fd9674c94ae2538bfdb2af1648aa1578ddb569283ef45a5cbc274d749958a97715615f3f01006b0d69e1bddcf858ac2e1526ed24bcde9dbdccf9c8193"

package_rust_crate
