#! /bin/sh

name=sonnet
version=6.25.0
revision=1
git_url="https://github.com/KDE/sonnet.git"
commit=f0ff2fda2fe72500bfc99a3f334f22590a64171d
imagedeps="cmake ninja-build pkg-config"
hostdeps="gcc pkg-config cmake qt6 extra-cmake-modules"
deps="core-libs qtbase6 qtdeclarative6"

configure() {
    kf6_configure \
        -DSONNET_NO_BACKENDS=ON
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
