#! /bin/sh

name=supertuxkart
version=1.5
revision=1
tarball_url="https://github.com/supertuxkart/stk-code/releases/download/${version}/SuperTuxKart-${version}-src.tar.gz"
tarball_blake2b="8becdf6be705c8549f3158ea0798fa46ec116c50f8002ff6a927c412a81534d195aaa40242a4cf68312a6336db559f85bd4bff5074ca4d54c18896f8aa3afddc"
imagedeps="python3"
hostdeps="gcc pkg-config cmake"
deps="core-libs mesa sdl2-compat freetype2 harfbuzz libpng libjpeg-turbo zlib bzip2 curl openssl libogg libvorbis libsamplerate"
clean_workdirs=no

configure() {
    cmake_configure \
        -DBUILD_SHARED_LIBS=OFF \
        -DCHECK_ASSETS=OFF \
        -DBUILD_RECORDER=OFF \
        -DUSE_MOJOAL=ON \
        -DUSE_WIIUSE=OFF \
        -DUSE_SYSTEM_ENET=OFF \
        -DUSE_SQLITE3=OFF \
        -DNO_SHADERC=on \
        -DCMAKE_POLICY_VERSION_MINIMUM=3.5
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
