#! /bin/sh

version=6.25.0
revision=1
git_url="https://github.com/KDE/ktexteditor.git"
commit=427b0ff258e0cbe48aca1bdf6c1c2782d1c5ff60
imagedeps="cmake ninja-build pkg-config libdbus-1-3 gettext libegl1 libgl1 libx11-6 libxkbcommon0 libsystemd0"
hostdeps="gcc pkg-config cmake qt6 extra-cmake-modules kconfig kcoreaddons"
deps="core-libs karchive kauth kcodecs kcolorscheme kcompletion kconfig kconfigwidgets kcoreaddons kguiaddons ki18n kio kitemviews kjobwidgets kparts kservice kwidgetsaddons kxmlgui pcre2 qtbase6 qtdeclarative6 qtspeech6 sonnet syntax-highlighting"

configure() {
    kf6_configure
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
