#! /bin/sh

revision=1
from_source=mlibc-headers
imagedeps="build-essential meson ninja-build"
hostdeps="gcc-bootstrap pkg-config"
builddeps="frigg libsmarter"
deps="mlibc-headers"
allow_network=yes

configure() {
        CFLAGS="$TARGET_CFLAGS" \
        CXXFLAGS="$TARGET_CXXFLAGS" \
        LDFLAGS="$TARGET_LDFLAGS" \
    meson_configure_noflags \
        -Dno_headers=true \
        -Ddefault_library=both
}

build() {
    ninja -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" ninja install
}
