#! /bin/sh

version=4.21.0
revision=1
tarball_url="https://archive.xfce.org/src/xfce/xfce4-panel/4.21/xfce4-panel-${version}.tar.xz"
tarball_blake2b="cf06cd31589e3f2ce854df7677e6ae54e59432f69cb552a1bd4069798d61a287b0e476e355a3f65c5862134b8a1b1b231fe5660fa7a1e306ca912da5796b4d5e"
hostdeps="gcc pkg-config glib2"
deps="core-libs cairo garcon exo libwnck libxfce4windowing"

configure() {
    meson_configure \
        -Dintrospection=false \
        -Dx11=enabled
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
