#! /bin/sh

repology_id=mlibc
version=5780d94544fd7697319ef01f84e763d735d34c5c
revision=1
git_url="https://github.com/zinnia-os/mlibc.git"
commit=${version}
shallow=no
imagedeps="meson ninja-build"
hostdeps="pkg-config"

configure() {
    meson_configure \
        -Dheaders_only=true
}

build() {
    ninja -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" ninja install
}
