#! /bin/sh

repology_id=mlibc
version=e8d0281132bec0757f59a71691b7118ac1609972
revision=1
git_url="https://github.com/zinnia-os/mlibc.git"
commit=${version}
shallow=no
imagedeps="meson ninja-build"
hostdeps="pkg-config"

configure() {
    meson_configure \
        -Dheaders_only=true
}

build() {
    ninja -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" ninja install
}
