#! /bin/sh

version=6.25.0
revision=1
git_url="https://github.com/KDE/kbookmarks.git"
commit=5cd64fdeb1db019bbcf201683defc416b4145395
imagedeps="cmake ninja-build pkg-config libdbus-1-3 gettext"
hostdeps="gcc pkg-config cmake qt6 extra-cmake-modules kconfig kcoreaddons"
deps="core-libs kconfig kconfigwidgets kcoreaddons kiconthemes kwidgetsaddons qtbase6"

configure() {
    kf6_configure
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
