#! /bin/sh

version=1.3.14
revision=1
git_url="https://github.com/silnrsi/graphite.git"
commit="142e1bda3439d2bd376bcac9c2b247c9532bacde"
hostdeps="gcc pkg-config cmake"
deps="core-libs"

configure() {
    cmake_configure
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
