#! /bin/sh

version=338cce63b22c85557c9274ad8ecfc8423a14024d
revision=1
git_url="https://github.com/managarm/libsmarter.git"
commit=${version}
imagedeps="meson ninja-build"
hostdeps="gcc-bootstrap pkg-config"

configure() {
    meson_configure \
        --includedir=share/libsmarter/include
}

build() {
    ninja -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" ninja install

    post_package_strip
}
