#! /bin/sh

version=6.25.0
revision=1
git_url="https://github.com/KDE/ksvg.git"
commit=9858f11839a14733065ee20ce29e1f2f4a9892ef
imagedeps="cmake ninja-build pkg-config libdbus-1-3 gettext libegl1 libgl1 libx11-6 libxkbcommon0 libsystemd0"
hostdeps="gcc pkg-config cmake qt6 extra-cmake-modules kconfig kcoreaddons"
deps="core-libs karchive kcolorscheme kconfig kcoreaddons kguiaddons kirigami qtbase6 qtdeclarative6 qtsvg6"

configure() {
    kf6_configure
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    qmldir="${dest_dir}/usr/lib/qt6/qml/org/kde/ksvg/qmldir"
    sed -i -e '/^linktarget /d' -e 's/^optional plugin /plugin /' -e '/^prefer /d' \
        "${qmldir}"

    post_package_strip
}
