#! /bin/sh

version=4.20.4
revision=1
tarball_url="https://archive.xfce.org/src/xfce/libxfce4windowing/4.20/libxfce4windowing-${version}.tar.bz2"
tarball_blake2b="ac02f754956a8b5750af4811e39904df534fe073be81a08c0434643de957fee847e01eee9b906869958763ff8b0d131bf60fc07235d8249c13a9afd071ab76e8"
imagedeps="build-essential python3-distutils-extra patchelf xfce4-dev-tools"
hostdeps="gcc glib2 pkg-config"
deps="core-libs glib2 gtk3 libwnck libdisplay-info libx11"

configure() {
    meson_configure \
        -Dintrospection=false \
        -Dtests=false \
        -Dgtk-doc=false
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
