#! /bin/sh

version=4.0.0
revision=1
tarball_url="https://gitlab.kitware.com/cmake/cmake/-/archive/v${version}/cmake-v${version}.tar.gz"
tarball_blake2b="659b8f54de89780326ff441620451c74b33712be32767800ce4f68d50fa67be2531f2073dc7123a213a9b81f1f99561a5078c5a9730a43600832c36970998212"
imagedeps="build-essential cmake libssl-dev"

configure() {
    "${source_dir}"/bootstrap \
        --prefix="${prefix}" \
        --parallel=${parallelism}
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR=${dest_dir} make install
    # Usually, you can use ${version} here, but CMake calls the current release 4.0.0
    cp -v ${base_dir}/support/Zinnia.cmake ${dest_dir}${prefix}/share/cmake-4.0/Modules/Platform/Zinnia.cmake
}
