#! /bin/sh

version=6.6.4
revision=1
git_url="https://github.com/KDE/kwayland.git"
commit=e754ecff7d2a248f4e951fda9d680bffa5bc5e1a
imagedeps="cmake ninja-build pkg-config gettext"
hostdeps="gcc pkg-config cmake qt6 extra-cmake-modules kconfig kcoreaddons wayland"
deps="core-libs libglvnd plasma-wayland-protocols qtbase6 qtwayland6 wayland wayland-protocols"

configure() {
    kf6_configure \
        -DWaylandScanner_EXECUTABLE=/usr/local/bin/wayland-scanner
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
