#! /bin/sh

from_source=karchive
revision=1
imagedeps="build-essential cmake ninja-build pkg-config zlib1g-dev"
hostdeps="gcc pkg-config qt6 extra-cmake-modules"

configure() {
    cmake -GNinja \
        -DCMAKE_INSTALL_PREFIX=${prefix} \
        -DCMAKE_BUILD_TYPE=Release \
        -DECM_DIR=${prefix}/share/ECM/cmake \
        -DQT_MAJOR_VERSION=6 \
        -DBUILD_TESTING=OFF \
        -DBUILD_QCH=FALSE \
        -DWITH_BZIP2=OFF \
        -DWITH_LIBLZMA=OFF \
        -DWITH_LIBZSTD=OFF \
        -DWITH_OPENSSL=OFF \
        -DKF_IGNORE_PLATFORM_CHECK=TRUE \
        "${source_dir}"
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .
}
