#! /bin/sh

version=0.3
revision=1
hostdeps="gcc pkg-config"
builddeps="mlibc"

build() {
    ${OS_TRIPLET}-gcc -o zinnia-init -static "${base_dir}/extras/zinnia-init/main.c"
}

package() {
    mkdir -p ${dest_dir}/usr/bin
    cp zinnia-init ${dest_dir}/usr/bin/zinnia-init
}
