#! /bin/sh

version=6.11.0
git_url="https://github.com/qt/qtlanguageserver.git"
commit=fa86fa006217f26d742127a6ef96677c87315b5e
imagedeps="ninja-build pkg-config python3 perl"
hostdeps="gcc pkg-config cmake qt6"
deps="core-libs qtbase6"
revision=1

configure() {
    cmake_configure \
        -DQT_HOST_PATH=/usr/local \
        -DQT_BUILD_EXAMPLES=OFF \
        -DQT_BUILD_TESTS=OFF
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
