#! /bin/sh

version=6.25.0
revision=1
git_url="https://github.com/KDE/kstatusnotifieritem.git"
commit=f3aecc13ccc51923de5ffa47bd8ffa365bed045d
imagedeps="cmake ninja-build pkg-config libdbus-1-3 gettext"
hostdeps="gcc pkg-config cmake qt6 extra-cmake-modules kconfig kcoreaddons"
deps="core-libs kwindowsystem qtbase6"

configure() {
    kf6_configure
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
