#! /bin/sh

version=6.11.0
git_url="https://github.com/qt/qtimageformats.git"
commit=ade536558e868143d615512a6873daabb8e9195b
imagedeps="ninja-build pkg-config python3 perl"
hostdeps="gcc pkg-config cmake qt6"
deps="core-libs libjpeg-turbo libtiff libwebp mesa qtbase6 zlib"
revision=1

configure() {
    cmake_configure \
        -DQT_HOST_PATH=/usr/local \
        -DQT_BUILD_EXAMPLES=OFF \
        -DQT_BUILD_TESTS=OFF \
        -DINPUT_webp=system \
        -DINPUT_tiff=system
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
