#! /bin/sh

version=6.25.0
revision=1
git_url="https://github.com/KDE/kirigami.git"
commit=ca176f5c0a18aea12b9e90c7563f53f075ca39d9
imagedeps="cmake ninja-build pkg-config libdbus-1-3 gettext libegl1 libgl1 libx11-6 libxkbcommon0 libsystemd0"
hostdeps="gcc pkg-config cmake qt6 extra-cmake-modules kconfig kcoreaddons"
deps="core-libs qt5compat qtbase6 qtdeclarative6 qtsvg6"

configure() {
    kf6_configure
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
