#! /bin/sh

version=6.25.0
revision=1
git_url="https://github.com/KDE/kcrash.git"
commit=415abf541297feb1b42dd8e6dc7fa045553699a1
imagedeps="cmake ninja-build pkg-config"
hostdeps="gcc pkg-config cmake qt6 extra-cmake-modules"
deps="core-libs kcoreaddons libice libx11 qtbase6"

configure() {
    kf6_configure
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
