#! /bin/sh

version=1.5.0
revision=1
git_url="https://gitlab.freedesktop.org/libinput/libei.git"
commit=19b64535408aa47abbc8151bc2c925afd6583851
imagedeps="pkg-config python3-jinja2 python3-attr"
hostdeps="gcc pkg-config"
deps="core-libs libevdev"

configure() {
    meson_configure \
        -Dliboeffis=disabled \
        -Dsd-bus-provider=auto \
        -Dtests=disabled \
        -Ddocumentation=[]
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
