#! /bin/sh

version=6.25.0
revision=1
git_url="https://github.com/KDE/breeze-icons.git"
commit=d1b94254e6e5b9c57595413e1766beaae8f08ff5
imagedeps="cmake ninja-build pkg-config python3 python3-lxml"
hostdeps="gcc pkg-config cmake qt6 extra-cmake-modules breeze-icons"
deps="core-libs qtbase6"

configure() {
    kf6_configure \
        -DKF6_HOST_TOOLING=/usr/local/bin \
        -DBINARY_ICONS_RESOURCE=OFF \
        -DSKIP_INSTALL_ICONS=OFF
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
