#! /bin/sh

version=6.11.0
git_url="https://github.com/qt/qttools.git"
commit=d1009a4a9e8bbc214f33e1b2f4466a55c0e3711d
imagedeps="ninja-build pkg-config python3 perl"
hostdeps="gcc pkg-config cmake qt6"
deps="core-libs qtbase6 qtdeclarative6"
revision=1

configure() {
    cmake_configure \
        -DQT_HOST_PATH=/usr/local \
        -DQT_BUILD_EXAMPLES=OFF \
        -DQT_BUILD_TESTS=OFF \
        -DCMAKE_DISABLE_FIND_PACKAGE_litehtml=ON \
        -DCMAKE_DISABLE_FIND_PACKAGE_Clang=ON \
        -DCMAKE_DISABLE_FIND_PACKAGE_WrapLibClang=ON \
        -DFEATURE_assistant=OFF \
        -DFEATURE_designer=OFF \
        -DFEATURE_qdoc=OFF \
        -DFEATURE_qtdiag=OFF \
        -DFEATURE_kmap2qmap=OFF
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
