#! /bin/sh

from_source=kpackage
revision=1
imagedeps="build-essential cmake ninja-build pkg-config libdbus-1-3"
hostdeps="gcc pkg-config qt6 extra-cmake-modules karchive kcoreaddons kconfig ki18n"

configure() {
    cmake -GNinja \
        -DCMAKE_INSTALL_PREFIX=${prefix} \
        -DCMAKE_BUILD_TYPE=Release \
        -DECM_DIR=${prefix}/share/ECM/cmake \
        -DQT_MAJOR_VERSION=6 \
        -DBUILD_TESTING=OFF \
        -DBUILD_QCH=FALSE \
        -DKF_IGNORE_PLATFORM_CHECK=TRUE \
        "${source_dir}"
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .
}
