#! /bin/sh

version=6.25.0
revision=1
git_url="https://github.com/KDE/kwindowsystem.git"
commit=d72d2591d564d0139ffa364dc05220b268710b0b
imagedeps="cmake ninja-build pkg-config"
hostdeps="gcc pkg-config cmake qt6 extra-cmake-modules wayland"
deps="core-libs qtbase6 qtdeclarative6 qtwayland6 wayland wayland-protocols plasma-wayland-protocols libice libx11 libxcb libxfixes xcb-util-keysyms xorg-proto"

configure() {
    kf6_configure \
        -DWaylandScanner_EXECUTABLE=/usr/local/bin/wayland-scanner
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
