#! /bin/sh

version=1.36
revision=1
tarball_url="https://gitlab.freedesktop.org/libevdev/evtest/-/archive/evtest-${version}/evtest-evtest-${version}.tar.bz2"
tarball_blake2b="79f6c06443488f1c49ad8382d8653591fd59aadea312a2564bcbf540feb398641ddf031a0335c28f39b298afa0422e9f6b8fee86e0bf972065e439e283bd191b"
source_hostdeps="autoconf automake"
hostdeps="gcc pkg-config autoconf automake"
deps="core-libs libevdev"

prepare() {
    autoreconf -fvi
}

configure() {
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
