#! /bin/sh

version=6.25.0
revision=1
git_url="https://github.com/KDE/kpty.git"
commit=8d670c30e1ffbf787a4947aa9a06080e95241114
imagedeps="cmake ninja-build pkg-config libdbus-1-3 gettext"
hostdeps="gcc pkg-config cmake qt6 extra-cmake-modules kconfig kcoreaddons"
deps="core-libs kcoreaddons ki18n qtbase6"

configure() {
    kf6_configure \
        -DCMAKE_DISABLE_FIND_PACKAGE_UTEMPTER=ON
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
