#! /bin/sh

version=0.26.4
revision=1
tarball_url="https://github.com/p11-glue/p11-kit/releases/download/${version}/p11-kit-${version}.tar.xz"
tarball_blake2b="91a8ff7679e34dbc9d3143c957ec2bba211da85f74c2aa3d150f3078de9387e1f04b4bbec56040e0c12249c1866e7ca191844c1dcdd6c1de29bec04e6d72ea96"
hostdeps="gcc pkg-config"
deps="core-libs libffi libtasn1"

configure() {
    meson_configure \
        -Dtrust_paths=/etc/pki/anchors \
        -Dbashcompdir=${prefix}/share/bash-completion/completions
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
