#! /bin/sh

version=6.25.0
revision=1
git_url="https://github.com/KDE/knotifyconfig.git"
commit=433a0776fc598b854be7ee550ea1a89895169119
imagedeps="cmake ninja-build pkg-config libdbus-1-3 gettext libegl1 libgl1 libx11-6 libxkbcommon0 libsystemd0"
hostdeps="gcc pkg-config cmake qt6 extra-cmake-modules kconfig kcoreaddons"
deps="core-libs kcompletion kconfig kconfigwidgets kcoreaddons ki18n kio knotifications qtbase6"

configure() {
    kf6_configure
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
