#! /bin/sh

version=6.6.4
revision=1
git_url="https://github.com/KDE/kscreenlocker.git"
commit=2de2e4006a9f1e5fd7270325deb1980c8ee6d99c
imagedeps="cmake ninja-build pkg-config libdbus-1-3 gettext libegl1 libgl1 libx11-6 libxkbcommon0 libsystemd0"
hostdeps="gcc pkg-config cmake qt6 extra-cmake-modules kconfig kcoreaddons kpackage kcmutils wayland"
deps="core-libs kcmutils kconfig kconfigwidgets kcoreaddons kcrash kglobalaccel ki18n kidletime kio kirigami knotifications ksvg kwindowsystem layer-shell-qt libkscreen libplasma libx11 libxcb libxi openpam plasma-activities qtbase6 qtdeclarative6 solid wayland xcb-util-keysyms"

configure() {
    kf6_configure \
        -DKF6_HOST_TOOLING=${KF6_HOST_TOOLING} \
        -DWaylandScanner_EXECUTABLE=/usr/local/bin/wayland-scanner
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
