#! /bin/sh

version=6.6.4
revision=1
git_url="https://github.com/KDE/layer-shell-qt.git"
commit=29fa2bb8e8c9e1be0057e47acd8184ebf0e2a331
imagedeps="cmake ninja-build pkg-config gettext libegl1 libgl1 libx11-6 libxkbcommon0 libsystemd0"
hostdeps="gcc pkg-config cmake qt6 extra-cmake-modules kconfig kcoreaddons wayland"
deps="core-libs libxkbcommon qtbase6 qtdeclarative6 qtwayland6 wayland wayland-protocols"

configure() {
    kf6_configure \
        -DWaylandScanner_EXECUTABLE=/usr/local/bin/wayland-scanner
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
