#! /bin/sh

version=6.6.4
revision=1
git_url="https://github.com/KDE/plasma-activities-stats.git"
commit=5059609a0ceda52e2d59464d372ad3dbdd01d614
imagedeps="cmake ninja-build pkg-config libdbus-1-3 gettext"
hostdeps="gcc pkg-config cmake qt6 extra-cmake-modules kconfig kcoreaddons"
deps="core-libs boost kconfig plasma-activities qtbase6"

configure() {
    kf6_configure
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
