#! /bin/sh

version=2.5.4
revision=1
tarball_url="https://ftp.fau.de/gnu/libtool/libtool-${version}.tar.xz"
tarball_blake2b="47de3c49a690d44d7ddd5e3b5e4090c91dc5fbb9c40fc4a3963e150fb7329326ee3e21b8c149974726171c4b0380028e0efc7a369c4f04357eea46f69852e1cc"
hostdeps="autoconf automake"
imagedeps="help2man build-essential"
source_hostdeps="autoconf automake"

prepare() {
        LIBTOOLIZE=true \
    autotools_recursive_regen
}

configure() {
    cp -rp "${source_dir}"/. ./

        CFLAGS="$HOST_CFLAGS" \
        CXXFLAGS="$HOST_CXXFLAGS" \
        LDFLAGS="$HOST_LDFLAGS" \
    ./configure \
        --prefix="${prefix}"
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    cp -pv /usr/local/share/autoconf/build-aux/config.sub "${dest_dir}${prefix}"/share/libtool/build-aux/
    cp -pv /usr/local/share/autoconf/build-aux/config.guess "${dest_dir}${prefix}"/share/libtool/build-aux/

        strip_command=strip \
    post_package_strip
}
