#! /bin/sh

version=6.6.4
revision=1
git_url="https://github.com/KDE/libksysguard.git"
commit=efe186082c72536f02a74d4d5096e342472f0b99
imagedeps="cmake ninja-build pkg-config libdbus-1-3 gettext libegl1 libgl1 libx11-6 libxkbcommon0 libsystemd0"
hostdeps="gcc pkg-config cmake qt6 extra-cmake-modules kconfig kcoreaddons"
deps="core-libs kauth kconfig kcoreaddons kiconthemes ki18n knewstuff kpackage kservice kwidgetsaddons qt5compat qtbase6 qtdeclarative6 solid zlib"

configure() {
    kf6_configure
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
