#! /bin/sh

from_source=breeze-icons
revision=1
imagedeps="build-essential cmake ninja-build pkg-config libgl-dev libegl-dev"
hostdeps="gcc pkg-config qt6 extra-cmake-modules"

configure() {
    cmake -GNinja \
        -DCMAKE_INSTALL_PREFIX=${prefix} \
        -DCMAKE_BUILD_TYPE=Release \
        -DECM_DIR=${prefix}/share/ECM/cmake \
        -DQT_MAJOR_VERSION=6 \
        -DBUILD_TESTING=OFF \
        -DBUILD_QCH=FALSE \
        -DKF_IGNORE_PLATFORM_CHECK=TRUE \
        "${source_dir}"
}

build() {
    cmake --build . -j${parallelism} --target generate-symbolic-dark qrcAlias
}

package() {
    install -Dm755 bin/generate-symbolic-dark "${dest_dir}${prefix}/bin/generate-symbolic-dark"
    install -Dm755 bin/qrcAlias "${dest_dir}${prefix}/bin/qrcAlias"
}
