#! /bin/sh

version=6.6.4
revision=1
git_url="https://github.com/KDE/kactivitymanagerd.git"
commit=fb3dcc4d2a606ac5d534b8509fc160ea64c712d0
imagedeps="cmake ninja-build pkg-config libdbus-1-3 gettext libegl1 libgl1 libx11-6 libxkbcommon0 libsystemd0"
hostdeps="gcc pkg-config cmake qt6 extra-cmake-modules kconfig kcoreaddons"
deps="core-libs boost kconfig kcoreaddons kcrash kdbusaddons kglobalaccel ki18n kio kwindowsystem qtbase6"

configure() {
    kf6_configure
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
