#! /bin/sh

version=6.6.4
revision=1
git_url="https://github.com/KDE/breeze.git"
commit=9eba34ac8f0fd082c8e14b9a4ee8e847a2afca7e
imagedeps="cmake ninja-build pkg-config libdbus-1-3 gettext libegl1 libgl1 libx11-6 libxkbcommon0 libsystemd0"
hostdeps="gcc pkg-config cmake qt6 extra-cmake-modules kconfig kcoreaddons kpackage kcmutils wayland"
deps="core-libs breeze-icons frameworkintegration kcmutils kconfig kconfigwidgets kcoreaddons kdecoration kguiaddons ki18n kiconthemes kirigami kwidgetsaddons kwindowsystem qtbase6 qtdeclarative6 qtsvg6"

configure() {
    kf6_configure \
        -DBUILD_QT6=ON \
        -DBUILD_QT5=OFF \
        -DKF6_HOST_TOOLING=${KF6_HOST_TOOLING}
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
