# Xorg configuration for Zinnia.

Section "ServerLayout"
    Identifier "Layout0"
    Screen     0 "Screen0"
EndSection

Section "ServerFlags"
    Option "DontVTSwitch" "true"
EndSection

Section "Module"
    Load "modesetting"
    Load "evdev"
EndSection

Section "Device"
    Identifier "Card0"
    Driver     "modesetting"
    Option     "kmsdev" "/dev/drm/card0"
EndSection

Section "Screen"
    Identifier "Screen0"
    Device     "Card0"
EndSection

# Keyboard layout for every auto-added keyboard.
Section "InputClass"
    Identifier "system-keyboard"
    MatchIsKeyboard "on"
    Option "XkbLayout" "us"
    Option "XkbModel"  "pc104"
EndSection
