#! /bin/sh

version=12.1.0
revision=1
tarball_url="https://github.com/harfbuzz/harfbuzz/releases/download/${version}/harfbuzz-${version}.tar.xz"
tarball_blake2b="126fd2f5028a2b99652dfca2948b43bf83f6ff498e067d561adbd686b24b4b496153cb6acc8ede412bd0ac407e08422fb40b0224206a7c45736969c10b62cfaa"
imagedeps="libglib2.0-dev-bin"
hostdeps="gcc pkg-config"
deps="core-libs graphite2 glib2 zlib freetype2 cairo icu"

configure() {
    meson_configure \
        -Dcpp_std=c++17 \
        -Dgraphite2=enabled \
        -Dglib=enabled \
        -Dgobject=enabled \
        -Dicu=enabled \
        -Dfreetype=enabled \
        -Dcairo=enabled \
        -Dtests=disabled \
        -Dintrospection=disabled
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
