#! /bin/sh

_base_patch=03
_patch=03
version=5.3.p${_patch}
revision=1
tarball_url="https://ftpmirror.gnu.org/gnu/bash/bash-5.3.tar.gz"
tarball_blake2b="82d1b54322bbd1e8c2a93380f1b2888a42a1d7186e504f41cee705a0fdd41463d8f20baa1755051e1396192f8ebd089524767d933a9e0b5fb76f2588601539bb"
source_allow_network=yes
imagedeps="build-essential"
hostdeps="gcc pkg-config"
deps="core-libs ncurses readline"

prepare() {
    if ! [ "${_base_patch}" = "${_patch}" ]; then
        for p in $(seq -w ${_base_patch} ${_patch}); do
            curl -L https://ftpmirror.gnu.org/gnu/bash/bash-5.3-patches/bash53-0$p | patch -p0
        done
    fi

    autotools_recursive_regen
}

configure() {
        bash_cv_getcwd_malloc=yes \
    autotools_configure \
        CFLAGS="$TARGET_CFLAGS \
            -DDEFAULT_PATH_VALUE='\"/usr/local/sbin:/usr/local/bin:/usr/bin\"' \
            -DSTANDARD_UTILS_PATH='\"/usr/bin\"' \
            -DSYS_BASHRC='\"/etc/bash.bashrc\"' \
            -DSYS_BASH_LOGOUT='\"/etc/bash.bash_logout\"' \
            -DNON_INTERACTIVE_LOGIN_SHELLS \
        " \
        --with-curses \
        --enable-readline \
        --without-bash-malloc \
        --with-installed-readline="${sysroot}${prefix}/lib"
}

build() {
    make -j${parallelism}
}

package() {
    make install DESTDIR="${dest_dir}"
    ln -s bash "${dest_dir}${prefix}"/bin/sh
    ln -s bash "${dest_dir}${prefix}"/bin/rbash

    mkdir -p "${dest_dir}"/etc
    cp -v "${base_dir}"/support/bash/bash.bashrc "${dest_dir}"/etc/
    cp -v "${base_dir}"/support/bash/bash.bash_logout "${dest_dir}"/etc/

    post_package_strip
}
