#! /bin/sh

version=6.25.0
revision=1
git_url="https://github.com/KDE/solid.git"
commit=5d5339caaba47b67d8fa03c6e6e32fd49a2a28bd
imagedeps="cmake ninja-build pkg-config libdbus-1-3"
hostdeps="gcc pkg-config cmake qt6 extra-cmake-modules"
deps="core-libs qtbase6 qtdeclarative6"

configure() {
    kf6_configure
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
