[LightDM]
greeter-user=root
lock-memory=false
minimum-vt=1
sessions-directory=/usr/share/xsessions:/usr/share/wayland-sessions
backup-logs=false

[Seat:*]
xserver-command=X -extension MIT-SHM
greeter-session=zinnia-greeter
user-session=plasma-zinnia
session-wrapper=/etc/lightdm/Xsession
session-setup-script=/etc/lightdm/setup-runtime-dir
