#! /bin/sh

version=6.6.4
revision=1
git_url="https://github.com/KDE/qqc2-breeze-style.git"
commit=d80a9d18b4525483a44c0153414d1929603de270
imagedeps="cmake ninja-build pkg-config libdbus-1-3 gettext libegl1 libgl1 libx11-6 libxkbcommon0 libsystemd0"
hostdeps="gcc pkg-config cmake qt6 extra-cmake-modules kconfig kcoreaddons"
deps="core-libs kcolorscheme kconfig kguiaddons kiconthemes kirigami qtbase6 qtdeclarative6"

configure() {
    kf6_configure
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
