#! /bin/sh

version=6.25.0
revision=1
git_url="https://github.com/KDE/kfilemetadata.git"
commit=693f1c16c55ea855b634286af890b384fb449dfe
imagedeps="cmake ninja-build pkg-config gettext"
hostdeps="gcc pkg-config cmake qt6 extra-cmake-modules"
deps="core-libs qtbase6 karchive kcodecs kconfig kcoreaddons ki18n"

configure() {
    kf6_configure \
        -DCMAKE_DISABLE_FIND_PACKAGE_Poppler=ON \
        -DCMAKE_DISABLE_FIND_PACKAGE_Taglib=ON \
        -DCMAKE_DISABLE_FIND_PACKAGE_LibExiv2=ON \
        -DCMAKE_DISABLE_FIND_PACKAGE_FFmpeg=ON \
        -DCMAKE_DISABLE_FIND_PACKAGE_EPub=ON \
        -DCMAKE_DISABLE_FIND_PACKAGE_QMobipocket6=ON \
        -DCMAKE_DISABLE_FIND_PACKAGE_libappimage=ON
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
