#! /bin/sh

name=cargo
from_source=cargo
revision=1
imagedeps="build-essential libssl-dev pkg-config cargo"
hostrundeps="gcc"
allow_network=yes

build() {
        CARGO_HOME="${build_dir}/.cargo" \
    cargo install \
        --target x86_64-unknown-linux-gnu \
        --target-dir "${build_dir}" \
        --path "${source_dir}" \
        -j${parallelism} \
        --root "${build_dir}/out"
}

package() {
        CARGO_HOME="${build_dir}/.cargo" \
    cargo install \
        --target x86_64-unknown-linux-gnu \
        --target-dir "${build_dir}" \
        --path "${source_dir}" \
        -j${parallelism} \
        --root "${dest_dir}${prefix}"

    # Strip binaries
    strip_command=strip \
    post_package_strip
}
