#! /bin/sh

name=rust
from_source=rust
revision=2
imagedeps="build-essential cmake ninja-build python3 curl git"
hostdeps="pkg-config cargo rust"
hostrundeps="gcc llvm"
deps="core-libs rust-libc rust-rustix rust-getrandom rust-nix rust-errno rust-socket2 rust-system-deps rust-libloading rust-libloading-09"
builddeps="mlibc"
allow_network=yes

prepare_rust_source() {
    rust_src="$(pwd -P)/rust-src"
    prepare_rust_toolchain_source "${rust_src}" "${sysroot_dir}/usr/src/rust"
}

configure() {
    cat > config.toml << EOF
change-id = "ignore"

[llvm]
targets = "X86;AArch64;RISCV;LoongArch"
link-shared = true
download-ci-llvm = false

[build]
target = ["${RUST_TRIPLET}", "${RUST_HOST_TRIPLET}"]
docs = false
python = "python3"
tools = ["src"]

[install]
prefix = "${prefix}"
sysconfdir = "etc"

[rust]
channel = "nightly"
codegen-tests = false
deny-warnings = false

[target.x86_64-unknown-linux-gnu]
llvm-config = "${prefix}/bin/llvm-config"

[target.${RUST_TRIPLET}]
llvm-config = "${prefix}/bin/llvm-config"
cc = "${OS_TRIPLET}-gcc"
cxx = "${OS_TRIPLET}-g++"
ar = "${OS_TRIPLET}-ar"
ranlib = "${OS_TRIPLET}-ranlib"
linker = "${OS_TRIPLET}-gcc"
EOF
}


build() {
    prepare_rust_source

        BOOTSTRAP_SKIP_TARGET_SANITY=1 \
    "${rust_src}"/x.py build rustc std --stage 2 -j${parallelism}
}

package() {
    prepare_rust_source

        BOOTSTRAP_SKIP_TARGET_SANITY=1 \
        DESTDIR="${dest_dir}" \
    "${rust_src}"/x.py install rustc std --stage 2 -j${parallelism}

    rm -rf "${dest_dir}${prefix}"/share/doc
    rm -rf "${dest_dir}${prefix}"/share/man

    mkdir -p "${dest_dir}${prefix}"/lib/rustlib/src/rust/library/
    cp -rp "${rust_src}"/library/. "${dest_dir}${prefix}"/lib/rustlib/src/rust/library/
}
