#! /bin/sh

version=0.23.1
revision=1
tarball_url="https://ftp.fau.de/gnu/gettext/gettext-${version}.tar.xz"
tarball_blake2b="08d10340f3d855a87a96594c6f2dcf72925394f02e86235090f8d272e0a27ce32e57a0fbaed61aaf61d7328ff30be076dccaecaa13832d8db3ec0a51786780b9"
repology_id=gettext
hostdeps="gcc automake autoconf libtool pkg-config"
deps="mlibc libgcc libstdc++ libiconv"
source_hostdeps="automake autoconf libtool pkg-config"

prepare() {
    ( cd gettext-runtime/libasprintf && autoreconf -fvi )
    ( cd gettext-runtime/intl && autoreconf -fvi )
    ( cd gettext-runtime && autoreconf -fvi )
    ( cd gettext-tools && autoreconf -fvi )
    ( cd libtextstyle && autoreconf -fvi )
    autoreconf -fvi
}

configure() {
        ACLOCAL=true \
        AUTOCONF=true \
        AUTOMAKE=true \
        AUTOHEADER=true \
    autotools_configure \
        --without-emacs \
        --without-lispdir \
        `# Normally this controls nls behavior in general, but the libintl` \
        `# subdir is skipped unless this is explicitly set.` \
        --enable-nls \
        `# This magic flag enables libintl.` \
        --with-included-gettext \
        --disable-c++ \
        --disable-libasprintf \
        --disable-java \
        --enable-threads=posix \
        --disable-curses \
        --without-git \
        --without-cvs \
        --without-bzip2 \
        --without-xz

    sed -i 's/touch $@//g' gettext-runtime/intl/Makefile
}

build() {
    make -C gettext-runtime/intl -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make -C gettext-runtime/intl install

    post_package_strip
}
