#! /bin/sh

from_source=kcmutils
revision=1
imagedeps="build-essential cmake ninja-build pkg-config"
hostdeps="gcc pkg-config qt6 extra-cmake-modules"

configure() {
    cat > CMakeLists.txt <<EOF
cmake_minimum_required(VERSION 3.16)
project(hostkcmutilstools)
find_package(ECM REQUIRED NO_MODULE)
set(CMAKE_MODULE_PATH \${ECM_MODULE_PATH})
include(KDEInstallDirs)
find_package(Qt6 REQUIRED COMPONENTS Core)
set(KF_VERSION "6.25.0")
add_subdirectory("${source_dir}/tools" tools)
EOF
    cmake -GNinja \
        -DCMAKE_INSTALL_PREFIX=${prefix} \
        -DCMAKE_BUILD_TYPE=Release \
        -DECM_DIR=${prefix}/share/ECM/cmake \
        -DQT_MAJOR_VERSION=6 \
        -DKF_IGNORE_PLATFORM_CHECK=TRUE \
        "$(pwd)"
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .
}
