#! /bin/sh

version=1.24.0
revision=1
tarball_url="https://gitlab.freedesktop.org/wayland/wayland/-/releases/${version}/downloads/wayland-${version}.tar.xz"
tarball_blake2b="7ac6ac1f33cb2cae60e4058478655eeabd4f8f8e0fe07f6b9b386967ed4b31bdaac571dc2b812f3189534e3e53797822ca39f829207e45c24b494f039f82a836"
imagedeps="pkg-config"
hostdeps="gcc pkg-config wayland"
deps="core-libs libxml2 libffi libexpat"

configure() {
    meson_configure \
        -Dtests=false \
        -Ddocumentation=false
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
