#!/bin/sh

export NO_AT_BRIDGE=1
export GTK_A11Y=none
export GDK_PIXBUF_MODULE_FILE=/usr/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache

gdk-pixbuf-query-loaders --update-cache 2>/dev/null || true
fc-cache -f 2>/dev/null || true

exec /usr/bin/lightdm-gtk-greeter "$@"
