#! /bin/sh

version=6.25.0
revision=1
git_url="https://github.com/KDE/kjobwidgets.git"
commit=a9490a1c60a5fd30acd3a6b6634abb5edc42e258
imagedeps="cmake ninja-build pkg-config libdbus-1-3"
hostdeps="gcc pkg-config cmake qt6 extra-cmake-modules"
deps="core-libs kcoreaddons knotifications kwidgetsaddons libice libx11 qtbase6 xorg-proto"

configure() {
    kf6_configure
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
