#! /bin/sh

version=6097e89af23cc4eec9f31a5a089f93c35e63edef
revision=1
git_url="https://github.com/osdev0/libgcc-binaries.git"
commit=${version}

package() {
    mkdir -p ${dest_dir}${prefix}/libgcc-binaries
    cp -rv ${source_dir}/. ${dest_dir}${prefix}/libgcc-binaries/
}
