#! /bin/sh

from_source=wayland
revision=1
imagedeps="build-essential pkg-config libffi-dev libexpat-dev libxml2-dev"
hostdeps="gcc pkg-config"

configure() {
    meson setup "${source_dir}" \
        --prefix=${prefix} \
        -Dtests=false \
        -Ddocumentation=false
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    strip_command=strip \
        post_package_strip
}
